# Generated by Django 4.1.2 on 2022-10-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0002_adminmailmessage_contactmodel_subscribers_musiclover"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmodel", old_name="message_detail", new_name="message",
        ),
    ]
