# Generated by Django 4.1.2 on 2022-11-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0014_alter_lyric_content"),
    ]

    operations = [
        migrations.RenameModel(old_name="Artist", new_name="Artiste",),
        migrations.RenameField(
            model_name="lyric", old_name="artist", new_name="artiste",
        ),
        migrations.RenameField(
            model_name="song", old_name="artist", new_name="artiste",
        ),
    ]
